# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Android.gitlab-ci.yml

# Read more about this script on this blog post https://about.gitlab.com/2018/10/24/setting-up-gitlab-ci-for-android-projects/, by Jason Lenny
# If you are interested in using Android with FastLane for publishing take a look at the Android-Fastlane template.

#script:
#  -  sudo apt install gitlab-runner

image: saschpe/android-ndk:32-jdk17.0.3_7-ndk23.1.7779620-cmake3.18.1


stages:
- build

before_script:
  - wget 	https://download.oracle.com/java/19/archive/jdk-19.0.2_linux-x64_bin.deb
  - apt-get -qqy install ./jdk-19.0.2_linux-x64_bin.deb
  - ls
  - whereis java
  - ls /
  - ls /opt
  - ls /opt/java
  - ls /opt/java/openjdk
  - cd MusicApps
  - chmod +x ./gradlew
  - java -version


#cache:
#  key: ${CI_PROJECT_ID}
#  paths:
#  - .gradle/

build:
  stage: build
  script:
  - ./gradlew assembleDebug
  artifacts:
    paths:
    - ./violin/build/outputs/apk/app-debug.apk

  

# Basic android and gradle stuff
# Check linting
lintDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew -Pci --console=plain lintDebug -PbuildDir=lint
  artifacts:
    paths:
    - ./violin/build/reports/lint-results-debug.html
    - ./common/build/reports/lint-results-debug.html

detekt:
    interruptible: true
    stage: build
    script:
      - ./gradlew :detekt
    artifacts:
      paths:
        - README.MD
        - LICENCE
        - ./violin/build/reports/detekt/detekt.html
        - ./common/build/reports/detekt/detekt.html

 
# Make Project
assembleDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - ./violin/build/outputs/

# Run all tests, if any fails, interrupt the pipeline(fail it)
#debugTests:
#  interruptible: true
#  stage: test
#  script:
#    - ./MusicApps/gradlew -Pci --console=plain :app:testDebug
