image: saschpe/android-ndk:32-jdk17.0.3_7-ndk23.1.7779620-cmake3.18.1

stages:
- build
- test

before_script:
  - wget 	https://download.oracle.com/java/19/archive/jdk-19.0.2_linux-x64_bin.deb
  - apt-get -qqy install ./jdk-19.0.2_linux-x64_bin.deb
  - export JAVA_HOME="/lib/jvm/jdk-19"
  - cd MusicApps
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
  - ./gradlew assemble
  artifacts:
    paths:
    - ./MusicApps/violin/build/outputs/apk/release/violin-release.apk

# Basic android and gradle stuff
# Check linting
lintDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew -Pci --console=plain lintDebug -PbuildDir=lint
  artifacts:
    paths:
    - ./MusicApps/violin/lint/reports/lint-results-debug.html
    - ./MusicApps/violin/lint/reports/lint-results-debug.html

detekt:
    interruptible: true
    stage: build
    script:
      - ./gradlew :violin:detekt
      - ./gradlew :common:detekt
    artifacts:
      paths:
        - ./MusicApps/violin/build/reports/detekt/detekt.html
        - ./MusicApps/common/build/reports/detekt/detekt.html

# Make Project
assembleDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - ./MusicApps/violin/build/outputs/apk/debug/violin-debug.apk


debugTests:
  interruptible: false
  stage: test
  script:
    - ./gradlew testDebug
  artifacts:
    when: always
    paths:
      - ./MusicApps/violin/build/reports/tests/testDebugUnitTest/*
      - ./MusicApps/common/build/reports/tests/testDebugUnitTest/*
